version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'h3nc4'
    reviewers:
      - 'h3nc4'
    open-pull-requests-limit: 50
    groups:
      radix:
        patterns:
          - '@radix-ui/*'
      react-core:
        patterns:
          - 'react'
          - 'react-dom'
          - 'react-icons'
      tailwind:
        patterns:
          - 'tailwind*'
          - '@tailwindcss/*'
      testing:
        patterns:
          - '@testing-library/*'
          - 'vitest'
          - '@vitest/*'
          - 'playwright'
      eslint:
        patterns:
          - 'eslint*'
          - '@eslint/*'
      types:
        patterns:
          - '@types/*'

  - package-ecosystem: 'cargo'
    directory: '/src/wasudoku-wasm'
    schedule:
      interval: 'daily'
    assignees:
      - 'h3nc4'
    reviewers:
      - 'h3nc4'
    open-pull-requests-limit: 50
    groups:
      wasm:
        patterns:
          - 'wasm-*'
          - 'wasm*'
          - 'js-sys'
          - 'web-sys'
      serde:
        patterns:
          - 'serde*'
