name: Image Build Check

on:
  pull_request:
    branches:
      - 'main'
      - 'release/*'
    paths:
      - 'ci.Dockerfile'
      - 'dev.Dockerfile'
      - 'scripts/wasm-deps.sh'
      - '.github/workflows/image-development.yaml'

jobs:
  check-images:
    name: Validate Image Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: ['ci.Dockerfile', 'dev.Dockerfile']
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run docker/setup-buildx-action
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Build image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          file: ./${{ matrix.file }}
          push: false
