name: Security Analysis

on:
  push:
    branches:
      - 'main'
      - 'release/*'
  pull_request:
    branches:
      - 'main'
      - 'release/*'
  schedule:
    - cron: '23 3 * * *' # Daily at 03:23 UTC

jobs:
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript-typescript', 'rust']

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: github/codeql-action/init@cf1bb45a277cb3c205638b2cd5c984db1c46a412 # v4
        with:
          languages: ${{ matrix.language }}
      - if: matrix.language == 'rust'
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src/wasudoku-wasm/target/
          key: ${{ matrix.language }}-${{ runner.os }}-cargo-${{ hashFiles('src/wasudoku-wasm/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.language }}-${{ runner.os }}-cargo-
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: 'wasm32-unknown-unknown'
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install UI dependencies
        run: npm ci
      - name: Build project for analysis
        run: |
          npm run wasm:build:prod
          npm run typecheck
      - uses: github/codeql-action/analyze@cf1bb45a277cb3c205638b2cd5c984db1c46a412 # v4
        with:
          category: '/language:${{matrix.language}}'
